'use client';

import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="border-t border-white/10 py-8 mt-12">
      <div className="container mx-auto px-6">
        {/* DISCLAIMER - NOT FINANCIAL ADVICE */}
        <div className="mb-6 p-4 bg-yellow-600/10 border border-yellow-600/30 rounded-lg">
          <p className="text-yellow-400 text-sm font-semibold mb-1">⚠️ DISCLAIMER - NOT FINANCIAL ADVICE</p>
          <p className="text-gray-400 text-xs leading-relaxed">
            All analysis, predictions, and signals provided on this website are generated by complex AI tools 
            and are for educational and informational purposes only. They are NOT financial advice. 
            Cryptocurrency trading involves substantial risk of loss and is not suitable for every investor. 
            The information provided is to help you leverage your understanding and potentially minimize losses, 
            but you should never trade with money you cannot afford to lose. Always do your own research 
            before making any investment decisions.
          </p>
        </div>
        
        {/* Footer Links */}
        <div className="flex flex-col md:flex-row justify-between items-center gap-4 text-sm">
          <div className="flex gap-6">
            <Link href="/dashboard" className="text-gray-400 hover:text-white transition">
              Dashboard
            </Link>
            <Link href="/news" className="text-gray-400 hover:text-white transition">
              News
            </Link>
            <Link href="/prices" className="text-gray-400 hover:text-white transition">
              Live Prices
            </Link>
            <Link href="/register" className="text-gray-400 hover:text-white transition">
              Register
            </Link>
          </div>
          
          <div className="flex gap-6">
            {/* GitHub Link */}
            <a
              href="https://github.com/Michaelmael"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 hover:text-white transition flex items-center gap-1"
            >
              <span>🐙</span> GitHub
            </a>
            {/* LinkedIn Link */}
            <a
              href="https://linkedin.com/in/mbugua-michael-07920b299"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 hover:text-white transition flex items-center gap-1"
            >
              <span>🔗</span> LinkedIn
            </a>
            {/* Email Contact */}
            <a
              href="mailto:mbuguamichael920@gmail.com"
              className="text-gray-400 hover:text-white transition flex items-center gap-1"
            >
              <span>✉️</span> Contact
            </a>
          </div>
        </div>
        
        {/* Copyright - All Rights Reserved */}
        <div className="text-center mt-6 pt-4 border-t border-white/5">
          <p className="text-gray-500 text-xs">
            © {new Date().getFullYear()} EarnOS. All rights reserved.
          </p>
          <p className="text-gray-600 text-xs mt-1">
            Built with Next.js • Real-time Crypto Intelligence
          </p>
        </div>
      </div>
    </footer>
  );
}
